/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.thecoffee.ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.thecoffee.components.ProductComponents;
import com.thecoffee.dao.SanPhamDAO;
import com.thecoffee.entity.SanPham;
import com.pagination.EventPagination;
import com.pagination.style.PaginationItemRenderStyle1;
import com.thecoffee.resource.Auth;
import com.thecoffee.resource.Constant;
import com.thecoffee.utils.MsgBox;
import com.thecoffee.utils.XImage;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daung
 */
public class DatHang extends javax.swing.JFrame {

    private int skip = 6;
    private int totalDrinkPage = 0;
    private int totalFoodPage = 0;
    private int currentPage = 0;
    private int MaLoaiSP = Constant.MA_DO_AN;
    private int soluong = 1;
    private int currentProduct = -1;
    private List<SanPham> listSanPham = new ArrayList<>();
    public List<SanPham> listGioHang = new ArrayList<>();
    private JLabel[] images;
    private JLabel[] titles;
    private JLabel[] prices;
    private JPanel[] productPanels;
    private List<ProductComponents> foodComponents = new ArrayList<>();
    private List<ProductComponents> drinkComponents = new ArrayList<>();
    private SanPhamDAO spdao = new SanPhamDAO();
    private SanPham selectedSp;
    private boolean isEdit = false;
    private int index = -1;
    private static AdminMain adminMain;

    /**
     * Creates new form UserMain
     */
    public DatHang(AdminMain adminMain) {
        initComponents();
        this.adminMain = adminMain;
        if (!Auth.role.equals(Constant.VAI_TRO_KHACH_HANG)) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        setLocationRelativeTo(null);
        initProductComponents();
        initPagination();
        loadData();
        hienThiSanPham();
        tblSanPham.setDefaultEditor(Object.class, null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(".\\appIcon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabCategory = new com.thecoffee.components.MaterialTabbed();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        product1 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        product2 = new javax.swing.JPanel();
        image2 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        product3 = new javax.swing.JPanel();
        image3 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        product4 = new javax.swing.JPanel();
        image4 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        product5 = new javax.swing.JPanel();
        image5 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        product6 = new javax.swing.JPanel();
        image6 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        JPanel7 = new javax.swing.JPanel();
        pagination1 = new com.pagination.Pagination();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        product7 = new javax.swing.JPanel();
        image7 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        product8 = new javax.swing.JPanel();
        image8 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        product9 = new javax.swing.JPanel();
        image9 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        product10 = new javax.swing.JPanel();
        image10 = new javax.swing.JLabel();
        title10 = new javax.swing.JLabel();
        price10 = new javax.swing.JLabel();
        product11 = new javax.swing.JPanel();
        image11 = new javax.swing.JLabel();
        title11 = new javax.swing.JLabel();
        price11 = new javax.swing.JLabel();
        product12 = new javax.swing.JPanel();
        image12 = new javax.swing.JLabel();
        title12 = new javax.swing.JLabel();
        price12 = new javax.swing.JLabel();
        JPanel9 = new javax.swing.JPanel();
        pagination2 = new com.pagination.Pagination();
        jPanel4 = new javax.swing.JPanel();
        btnDetails = new javax.swing.JButton();
        formPrice = new javax.swing.JLabel();
        formTitle = new javax.swing.JLabel();
        btnGiam = new javax.swing.JButton();
        btnTang = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        formTongTien = new javax.swing.JLabel();
        formAddBtn = new javax.swing.JButton();
        formImage = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnScan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabCategory.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabCategoryStateChanged(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        product1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product1Layout = new javax.swing.GroupLayout(product1);
        product1.setLayout(product1Layout);
        product1Layout.setHorizontalGroup(
            product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        product1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {price1, title1});

        product1Layout.setVerticalGroup(
            product1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product1);

        product2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product2Layout = new javax.swing.GroupLayout(product2);
        product2.setLayout(product2Layout);
        product2Layout.setHorizontalGroup(
            product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product2Layout.setVerticalGroup(
            product2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product2);

        product3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product3Layout = new javax.swing.GroupLayout(product3);
        product3.setLayout(product3Layout);
        product3Layout.setHorizontalGroup(
            product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product3Layout.setVerticalGroup(
            product3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product3);

        product4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product4Layout = new javax.swing.GroupLayout(product4);
        product4.setLayout(product4Layout);
        product4Layout.setHorizontalGroup(
            product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product4Layout.setVerticalGroup(
            product4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product4);

        product5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product5Layout = new javax.swing.GroupLayout(product5);
        product5.setLayout(product5Layout);
        product5Layout.setHorizontalGroup(
            product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(product5Layout.createSequentialGroup()
                        .addGroup(product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(image5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        product5Layout.setVerticalGroup(
            product5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product5);

        product6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product6Layout = new javax.swing.GroupLayout(product6);
        product6.setLayout(product6Layout);
        product6Layout.setHorizontalGroup(
            product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product6Layout.setVerticalGroup(
            product6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image6, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(product6);

        JPanel7.setBackground(new java.awt.Color(64, 122, 237));
        JPanel7.setPreferredSize(new java.awt.Dimension(639, 40));

        pagination1.setOpaque(false);

        javax.swing.GroupLayout JPanel7Layout = new javax.swing.GroupLayout(JPanel7);
        JPanel7.setLayout(JPanel7Layout);
        JPanel7Layout.setHorizontalGroup(
            JPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel7Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(pagination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        JPanel7Layout.setVerticalGroup(
            JPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagination1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addComponent(JPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabCategory.addTab("Đồ Ăn", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(663, 471));

        jPanel13.setLayout(new java.awt.GridLayout(2, 3, 4, 4));

        product7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product7Layout = new javax.swing.GroupLayout(product7);
        product7.setLayout(product7Layout);
        product7Layout.setHorizontalGroup(
            product7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product7Layout.setVerticalGroup(
            product7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product7);

        product8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product8Layout = new javax.swing.GroupLayout(product8);
        product8.setLayout(product8Layout);
        product8Layout.setHorizontalGroup(
            product8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product8Layout.setVerticalGroup(
            product8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image8, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product8);

        product9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product9Layout = new javax.swing.GroupLayout(product9);
        product9.setLayout(product9Layout);
        product9Layout.setHorizontalGroup(
            product9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product9Layout.setVerticalGroup(
            product9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image9, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product9);

        product10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product10Layout = new javax.swing.GroupLayout(product10);
        product10.setLayout(product10Layout);
        product10Layout.setHorizontalGroup(
            product10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product10Layout.setVerticalGroup(
            product10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product10);

        product11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product11Layout = new javax.swing.GroupLayout(product11);
        product11.setLayout(product11Layout);
        product11Layout.setHorizontalGroup(
            product11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product11Layout.setVerticalGroup(
            product11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image11, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product11);

        product12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        product12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout product12Layout = new javax.swing.GroupLayout(product12);
        product12.setLayout(product12Layout);
        product12Layout.setHorizontalGroup(
            product12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(product12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        product12Layout.setVerticalGroup(
            product12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image12, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(product12);

        JPanel9.setBackground(new java.awt.Color(64, 122, 237));
        JPanel9.setPreferredSize(new java.awt.Dimension(639, 40));

        pagination2.setOpaque(false);

        javax.swing.GroupLayout JPanel9Layout = new javax.swing.GroupLayout(JPanel9);
        JPanel9.setLayout(JPanel9Layout);
        JPanel9Layout.setHorizontalGroup(
            JPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel9Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(pagination2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        JPanel9Layout.setVerticalGroup(
            JPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagination2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(JPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        tabCategory.addTab("Đồ Uống", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetails.setText("Thanh Toán");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        formPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        formTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGiam.setText("-");
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        btnTang.setText("+");
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.setText("1");

        formTongTien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        formAddBtn.setText("Thêm");
        formAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAddBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Giá:");

        jLabel2.setText("Thành tiền:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formImage, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuong)
                    .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(formTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Giá", "Số lượng", "Thành tiền"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SẢN PHẨM ĐÃ THÊM");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Tìm kiếm:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnScan.setText("Quét mã");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScan))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(698, 698, 698))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(tabCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product1MouseClicked
        setForm(0);
    }//GEN-LAST:event_product1MouseClicked

    private void product2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product2MouseClicked
        setForm(1);
    }//GEN-LAST:event_product2MouseClicked

    private void product3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product3MouseClicked
        setForm(2);
    }//GEN-LAST:event_product3MouseClicked

    private void product4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product4MouseClicked
        setForm(3);
    }//GEN-LAST:event_product4MouseClicked

    private void product5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product5MouseClicked
        setForm(4);
    }//GEN-LAST:event_product5MouseClicked

    private void product6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product6MouseClicked
        setForm(5);
    }//GEN-LAST:event_product6MouseClicked

    private void product7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product7MouseClicked
        setForm(0);
    }//GEN-LAST:event_product7MouseClicked

    private void product11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product11MouseClicked
        setForm(4);
    }//GEN-LAST:event_product11MouseClicked

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        giamSoLuong();
    }//GEN-LAST:event_btnGiamActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed
        tangSoLuong();
    }//GEN-LAST:event_btnTangActionPerformed

    private void formAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAddBtnActionPerformed
        themSanPham();
    }//GEN-LAST:event_formAddBtnActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        search();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        new ThanhToanUI(this, adminMain, true).setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (evt.getClickCount() == 2) {
            int line = tblSanPham.getSelectedRow();
            if (line >= 0) {
                selectedSp = listGioHang.get(line);
                setForm(selectedSp);
            }
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void product8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product8MouseClicked
        setForm(1);
    }//GEN-LAST:event_product8MouseClicked

    private void product9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product9MouseClicked
        setForm(2);
    }//GEN-LAST:event_product9MouseClicked

    private void product10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product10MouseClicked
        setForm(3);
    }//GEN-LAST:event_product10MouseClicked

    private void product12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product12MouseClicked
        setForm(5);
    }//GEN-LAST:event_product12MouseClicked

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        new Scan(this).setVisible(true);
    }//GEN-LAST:event_btnScanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadPagination(currentPage + 1);
    }//GEN-LAST:event_formWindowOpened

    private void tabCategoryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabCategoryStateChanged
        // TODO add your handling code here:
        changeTab();
    }//GEN-LAST:event_tabCategoryStateChanged

    /**
     * @param args the command line arguments
     */
    private void initPagination() {
        pagination1.setPaginationItemRender(new PaginationItemRenderStyle1());
        pagination1.addEventPagination(new EventPagination() {
            @Override
            public void pageChanged(int page) {
                System.out.println(page);
                loadPagination(page);
                hienThiSanPham();
            }
        });
        pagination2.setPaginationItemRender(new PaginationItemRenderStyle1());
        pagination2.addEventPagination(new EventPagination() {
            @Override
            public void pageChanged(int page) {
                loadPagination(page);
                System.out.println(page);
                hienThiSanPham();
            }
        });
    }

    private void loadPagination(int page) {
        totalDrinkPage = (int) Math.ceil(spdao.getTotalByCategory(Constant.MA_DO_UONG) * 1.0 / skip);
        totalFoodPage = (int) Math.ceil(spdao.getTotalByCategory(Constant.MA_DO_AN) * 1.0 / skip);
        while (!listSanPham.isEmpty()) {
            listSanPham.remove(0);
        }
        listSanPham = spdao.selectByLoaiSanPhamWithPaginatio(MaLoaiSP, skip * (page - 1), skip);
        pagination1.setPagegination(page, totalFoodPage);
        pagination2.setPagegination(page, totalDrinkPage);
    }

    private void initProductComponents() {
        images = new JLabel[]{image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12};
        titles = new JLabel[]{title1, title2, title3, title4, title5, title6, title7, title8, title9, title10, title11, title12};
        prices = new JLabel[]{price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, price11, price12};
        productPanels = new JPanel[]{product1, product2, product3, product4, product5, product6, product7, product8, product9, product10, product11, product12};
        for (int i = 0; i < 12; i++) {
            if (i < 6) {
                foodComponents.add(new ProductComponents(productPanels[i], images[i], titles[i], prices[i]));
            } else {
                drinkComponents.add(new ProductComponents(productPanels[i], images[i], titles[i], prices[i]));
            }
        }
    }

    public void loadData() {
        while (!listSanPham.isEmpty()) {
            listSanPham.remove(0);
        }
        listSanPham = spdao.selectByLoaiSanPhamWithPaginatio(MaLoaiSP, skip * currentPage, skip);
    }

    private void changeTab() {
        MaLoaiSP = tabCategory.getSelectedIndex() + 1;
        currentPage = 0;
        loadPagination(currentPage + 1);
        loadData();
        hienThiSanPham();
    }

    private void hienThiSanPham() {
        int end = foodComponents.size() < listSanPham.size() ? foodComponents.size() : listSanPham.size();
        if (MaLoaiSP == Constant.MA_DO_AN) {
            for (int i = 0; i < foodComponents.size(); i++) {
                if (i < end) {
                    foodComponents.get(i).show(listSanPham.get(i));
                } else {
                    foodComponents.get(i).clear();
                }
            }
        } else if (MaLoaiSP == Constant.MA_DO_UONG) {
            for (int i = 0; i < drinkComponents.size(); i++) {
                if (i < end) {
                    drinkComponents.get(i).show(listSanPham.get(i));
                } else {
                    drinkComponents.get(i).clear();
                }
            }
        }
    }

    public void setForm(int index) {
        if (index < listSanPham.size()) {
            isEdit = false;
            currentProduct = index;
            soluong = 1;
            SanPham sp = listSanPham.get(index);
            XImage.setLabelIcon(formImage, sp.getAnh());
            formTitle.setText(sp.getTen());
            formPrice.setText(sp.getGia() + "");
            thayDoiSoLuong();
            formAddBtn.setText("Thêm");
        }
    }

    public void setForm(SanPham sp) {
        isEdit = true;
        XImage.setLabelIcon(formImage, sp.getAnh());
        formTitle.setText(sp.getTen());
        formPrice.setText(sp.getGia() + "");
        txtSoLuong.setText(sp.getSoluong() + "");
        formTongTien.setText(sp.getGia() * sp.getSoluong() + "");
        formAddBtn.setText("Cập nhật");
    }

    private void clearForm() {
        XImage.setLabelIcon(formImage, "");
        formTitle.setText("");
        formPrice.setText("");
        txtSoLuong.setText("");
        formTongTien.setText("");
        soluong = 1;
        currentProduct = -1;
        isEdit = false;
        formAddBtn.setText("Thêm");
    }

    private void tangSoLuong() {
        if (isEdit) {
            int sl = selectedSp.getSoluong() + 1;
            selectedSp.setSoluong(sl);
            fillTable();
        } else {
            if (!formTitle.getText().isEmpty()) {
                soluong++;
            }
        }
        thayDoiSoLuong();
    }

    private void giamSoLuong() {
        if (isEdit) {
            int sl = selectedSp.getSoluong() - 1;
            if (sl == 0) {
                listGioHang.remove(selectedSp);
                clearForm();
            } else {
                selectedSp.setSoluong(sl);
            }
            fillTable();
        } else {
            if (soluong > 1 && !formTitle.getText().isEmpty()) {
                soluong--;
            }
        }
        thayDoiSoLuong();
    }

    private void thayDoiSoLuong() {
        try {
            if (isEdit) {
                txtSoLuong.setText(selectedSp.getSoluong() + "");
            } else {
                txtSoLuong.setText(soluong + "");
            }
            int sl = Integer.parseInt(txtSoLuong.getText());
            formTongTien.setText(Double.parseDouble(formPrice.getText()) * soluong + "");
        } catch (Exception e) {
            formTongTien.setText("Số lượng không hợp lệ");
        }

    }

    private void dangXuat() {
        this.dispose();
        new Login().setVisible(true);
    }

    public void search() {
        if (txtSearch.getText().trim().equals("")) {
            loadData();
        } else {
            listSanPham = spdao.search(txtSearch.getText());
        }
        hienThiSanPham();
    }

    private void themSanPham() {
        if (isEdit) {
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                if (sl <= 0) {
                    MsgBox.alert(this, "Số lượng phải lớn hơn 0");
                } else {
                    selectedSp.setSoluong(sl);
                    fillTable();
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Số lượng không hợp lệ");
            }
        } else {
            if (currentProduct > -1) {
                boolean isExist = false;
                SanPham sp = listSanPham.get(currentProduct);

                for (SanPham sanPham : listGioHang) {
                    if (sanPham.getMaSP() == sp.getMaSP()) {
                        sanPham.setSoluong(sanPham.getSoluong() + Integer.parseInt(txtSoLuong.getText()));
                        isExist = true;
                    }
                }
                if (!isExist) {
                    sp.setSoluong(Integer.parseInt(txtSoLuong.getText()));
                    listGioHang.add(sp);
                }
                clearForm();
                fillTable();
            }
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        for (SanPham sanPham : listGioHang) {
            model.addRow(sanPham.toRowOrder());
        }
    }

    public void scan(String id) {
        listSanPham = spdao.search(id);
        if (listSanPham.isEmpty()) {
            MsgBox.alert(this, "Không tìm thấy sản phẩm!!!");
            loadData();
            clearForm();
        } else {
            hienThiSanPham();
            setForm(0);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatHang(adminMain).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel7;
    private javax.swing.JPanel JPanel9;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnScan;
    private javax.swing.JButton btnTang;
    private javax.swing.JButton formAddBtn;
    private javax.swing.JLabel formImage;
    private javax.swing.JLabel formPrice;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel formTongTien;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image10;
    private javax.swing.JLabel image11;
    private javax.swing.JLabel image12;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private com.pagination.Pagination pagination1;
    private com.pagination.Pagination pagination2;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price10;
    private javax.swing.JLabel price11;
    private javax.swing.JLabel price12;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JPanel product1;
    private javax.swing.JPanel product10;
    private javax.swing.JPanel product11;
    private javax.swing.JPanel product12;
    private javax.swing.JPanel product2;
    private javax.swing.JPanel product3;
    private javax.swing.JPanel product4;
    private javax.swing.JPanel product5;
    private javax.swing.JPanel product6;
    private javax.swing.JPanel product7;
    private javax.swing.JPanel product8;
    private javax.swing.JPanel product9;
    private com.thecoffee.components.MaterialTabbed tabCategory;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title12;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

}
