/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.thecoffee.ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.thecoffee.components.DonHangComponent;
import com.thecoffee.dao.DonHangChiTietDAO;
import com.thecoffee.dao.DonHangDAO;
import com.thecoffee.entity.DonHang;
import com.thecoffee.entity.DonHangChiTiet;
import com.thecoffee.utils.MsgBox;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author daung
 */
public class DonHangChiTietUI extends javax.swing.JDialog {

    private static DonHang donhang;
    private static AdminMain admain;
    private static DonHangJDialog dhJdialog;
    private JLabel[] images;
    private JLabel[] prices;
    private JLabel[] numbers;
    private JLabel[] titles;
    private JLabel[] edits;
    List<DonHangComponent> list = new ArrayList<>();
    List<DonHangChiTiet> listDhct = new ArrayList<>();
    List<DonHangChiTiet> listXoa = new ArrayList<>();
    private DonHangDAO dhdao = new DonHangDAO();
    private DonHangChiTietDAO dhctdao = new DonHangChiTietDAO();
    private int totalPage = 0;
    private int currentPage = 0;
    private int skip = 10;
    private int discount = 0;
    private int discountPercent = 0;

    /**
     * Creates new form GioHangJDialog
     */
    public DonHangChiTietUI(JDialog parent, boolean modal, DonHang dh, AdminMain admain, DonHangJDialog dhJdialog) {
        super(parent, modal);
        this.donhang = dh;
        this.admain = admain;
        this.dhJdialog = dhJdialog;
        initComponents();
        setLocationRelativeTo(null);
        initDonHangComponents();
        loadData();
        discountPercent = (int) ((donhang.getGiamGia() * 100 - donhang.getDiem()) / (donhang.getGiamGia() - donhang.getDiem() + donhang.getThanhToan()));
        initPagination();
        fillData();
        setForm();
        themNutSuaDonHang();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(".\\appIcon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wrapper1 = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        number1 = new javax.swing.JLabel();
        edit1 = new javax.swing.JLabel();
        wrapper2 = new javax.swing.JPanel();
        edit2 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        wrapper3 = new javax.swing.JPanel();
        edit3 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        number3 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        wrapper4 = new javax.swing.JPanel();
        edit4 = new javax.swing.JLabel();
        image4 = new javax.swing.JLabel();
        number4 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        wrapper5 = new javax.swing.JPanel();
        edit5 = new javax.swing.JLabel();
        image5 = new javax.swing.JLabel();
        number5 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        wrapper6 = new javax.swing.JPanel();
        edit6 = new javax.swing.JLabel();
        image6 = new javax.swing.JLabel();
        number6 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        wrapper7 = new javax.swing.JPanel();
        edit7 = new javax.swing.JLabel();
        image7 = new javax.swing.JLabel();
        number7 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        wrapper8 = new javax.swing.JPanel();
        edit8 = new javax.swing.JLabel();
        image8 = new javax.swing.JLabel();
        number8 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        wrapper9 = new javax.swing.JPanel();
        edit9 = new javax.swing.JLabel();
        image9 = new javax.swing.JLabel();
        number9 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        wrapper10 = new javax.swing.JPanel();
        edit10 = new javax.swing.JLabel();
        image10 = new javax.swing.JLabel();
        number10 = new javax.swing.JLabel();
        price10 = new javax.swing.JLabel();
        title10 = new javax.swing.JLabel();
        pagination = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttongSoLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPoint = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đơn hàng chi tiết");

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 4, 4));

        wrapper1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title1.setText(" ");

        price1.setText(" ");

        number1.setText(" ");

        edit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit1.setText(" ");
        edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wrapper1Layout = new javax.swing.GroupLayout(wrapper1);
        wrapper1.setLayout(wrapper1Layout);
        wrapper1Layout.setHorizontalGroup(
            wrapper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper1Layout.setVerticalGroup(
            wrapper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper1Layout.createSequentialGroup()
                        .addComponent(title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit1))
                    .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper1);

        wrapper2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit2.setText(" ");
        edit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit2MouseClicked(evt);
            }
        });

        number2.setText(" ");

        price2.setText(" ");

        title2.setText(" ");

        javax.swing.GroupLayout wrapper2Layout = new javax.swing.GroupLayout(wrapper2);
        wrapper2.setLayout(wrapper2Layout);
        wrapper2Layout.setHorizontalGroup(
            wrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper2Layout.setVerticalGroup(
            wrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper2Layout.createSequentialGroup()
                        .addComponent(title2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit2))
                    .addComponent(image2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper2);

        wrapper3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit3.setText(" ");
        edit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit3MouseClicked(evt);
            }
        });

        number3.setText(" ");

        price3.setText(" ");

        title3.setText(" ");

        javax.swing.GroupLayout wrapper3Layout = new javax.swing.GroupLayout(wrapper3);
        wrapper3.setLayout(wrapper3Layout);
        wrapper3Layout.setHorizontalGroup(
            wrapper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper3Layout.setVerticalGroup(
            wrapper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper3Layout.createSequentialGroup()
                        .addComponent(title3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit3))
                    .addComponent(image3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper3);

        wrapper4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit4.setText(" ");
        edit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit4MouseClicked(evt);
            }
        });

        number4.setText(" ");

        price4.setText(" ");

        title4.setText(" ");

        javax.swing.GroupLayout wrapper4Layout = new javax.swing.GroupLayout(wrapper4);
        wrapper4.setLayout(wrapper4Layout);
        wrapper4Layout.setHorizontalGroup(
            wrapper4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper4Layout.setVerticalGroup(
            wrapper4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper4Layout.createSequentialGroup()
                        .addComponent(title4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit4))
                    .addComponent(image4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper4);

        wrapper5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit5.setText(" ");
        edit5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit5MouseClicked(evt);
            }
        });

        number5.setText(" ");

        price5.setText(" ");

        title5.setText(" ");

        javax.swing.GroupLayout wrapper5Layout = new javax.swing.GroupLayout(wrapper5);
        wrapper5.setLayout(wrapper5Layout);
        wrapper5Layout.setHorizontalGroup(
            wrapper5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price5, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper5Layout.setVerticalGroup(
            wrapper5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper5Layout.createSequentialGroup()
                        .addComponent(title5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit5))
                    .addComponent(image5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper5);

        wrapper6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit6.setText(" ");
        edit6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit6MouseClicked(evt);
            }
        });

        number6.setText(" ");

        price6.setText(" ");

        title6.setText(" ");

        javax.swing.GroupLayout wrapper6Layout = new javax.swing.GroupLayout(wrapper6);
        wrapper6.setLayout(wrapper6Layout);
        wrapper6Layout.setHorizontalGroup(
            wrapper6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title6, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price6, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper6Layout.setVerticalGroup(
            wrapper6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper6Layout.createSequentialGroup()
                        .addComponent(title6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit6))
                    .addComponent(image6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper6);

        wrapper7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit7.setText(" ");
        edit7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit7MouseClicked(evt);
            }
        });

        number7.setText(" ");

        price7.setText(" ");

        title7.setText(" ");

        javax.swing.GroupLayout wrapper7Layout = new javax.swing.GroupLayout(wrapper7);
        wrapper7.setLayout(wrapper7Layout);
        wrapper7Layout.setHorizontalGroup(
            wrapper7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title7, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price7, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper7Layout.setVerticalGroup(
            wrapper7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper7Layout.createSequentialGroup()
                        .addComponent(title7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit7))
                    .addComponent(image7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper7);

        wrapper8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit8.setText(" ");
        edit8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit8MouseClicked(evt);
            }
        });

        number8.setText(" ");

        price8.setText(" ");

        title8.setText(" ");

        javax.swing.GroupLayout wrapper8Layout = new javax.swing.GroupLayout(wrapper8);
        wrapper8.setLayout(wrapper8Layout);
        wrapper8Layout.setHorizontalGroup(
            wrapper8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title8, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price8, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper8Layout.setVerticalGroup(
            wrapper8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper8Layout.createSequentialGroup()
                        .addComponent(title8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit8))
                    .addComponent(image8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper8);

        wrapper9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit9.setText(" ");
        edit9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit9MouseClicked(evt);
            }
        });

        number9.setText(" ");

        price9.setText(" ");

        title9.setText(" ");

        javax.swing.GroupLayout wrapper9Layout = new javax.swing.GroupLayout(wrapper9);
        wrapper9.setLayout(wrapper9Layout);
        wrapper9Layout.setHorizontalGroup(
            wrapper9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title9, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price9, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper9Layout.setVerticalGroup(
            wrapper9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper9Layout.createSequentialGroup()
                        .addComponent(title9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit9))
                    .addComponent(image9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper9);

        wrapper10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        edit10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edit10.setText(" ");
        edit10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit10MouseClicked(evt);
            }
        });

        number10.setText(" ");

        price10.setText(" ");

        title10.setText(" ");

        javax.swing.GroupLayout wrapper10Layout = new javax.swing.GroupLayout(wrapper10);
        wrapper10.setLayout(wrapper10Layout);
        wrapper10Layout.setHorizontalGroup(
            wrapper10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapper10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(title10, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(price10, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(number10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edit10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        wrapper10Layout.setVerticalGroup(
            wrapper10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapper10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapper10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrapper10Layout.createSequentialGroup()
                        .addComponent(title10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit10))
                    .addComponent(image10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(wrapper10);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tổng SL:");

        txttongSoLuong.setEditable(false);
        txttongSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Tổng tiền:");

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Điểm:");

        txtPoint.setEditable(false);
        txtPoint.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Giảm giá:");

        txtDiscount.setEditable(false);
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Thanh toán:");

        txtPayment.setEditable(false);
        txtPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THÔNG TIN THANH TOÁN");

        jPanel3.setLayout(new java.awt.GridLayout(3, 1, 2, 0));

        jLabel11.setText("Tên:");

        txtName.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addComponent(txtName))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);

        jLabel12.setText("SĐT:");

        txtPhone.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addComponent(txtPhone))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5);

        jLabel14.setText("Mã khuyến mãi:");

        txtVoucher.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel7);

        btnAction.setText("Lưu");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAction, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txttongSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(txtTotal)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(24, 24, 24)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPoint)
                                            .addComponent(txtPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(txtDiscount))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiscount, txtPayment, txtTotal, txttongSoLuong});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pagination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagination, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseClicked
        suaThongTin(0);
    }//GEN-LAST:event_edit1MouseClicked

    private void edit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit2MouseClicked
        suaThongTin(1);
    }//GEN-LAST:event_edit2MouseClicked

    private void edit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit3MouseClicked
        suaThongTin(2);
    }//GEN-LAST:event_edit3MouseClicked

    private void edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseClicked
        suaThongTin(3);
    }//GEN-LAST:event_edit4MouseClicked

    private void edit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit5MouseClicked
        suaThongTin(4);
    }//GEN-LAST:event_edit5MouseClicked

    private void edit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit6MouseClicked
        suaThongTin(5);
    }//GEN-LAST:event_edit6MouseClicked

    private void edit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit7MouseClicked
        suaThongTin(6);
    }//GEN-LAST:event_edit7MouseClicked

    private void edit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit8MouseClicked
        suaThongTin(7);
    }//GEN-LAST:event_edit8MouseClicked

    private void edit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit9MouseClicked
        suaThongTin(8);
    }//GEN-LAST:event_edit9MouseClicked

    private void edit10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit10MouseClicked
        suaThongTin(9);
    }//GEN-LAST:event_edit10MouseClicked

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        thayDoiThongTinDonHang();
    }//GEN-LAST:event_btnActionActionPerformed

    private void setForm() {
        int tongSoluong = 0;
        for (int i = 0; i < listDhct.size(); i++) {
            tongSoluong += listDhct.get(i).getSoLuong();
        }
        txttongSoLuong.setText("" + tongSoluong);
        txtTotal.setText(donhang.getThanhToan() + donhang.getGiamGia() + "");
        txtPoint.setText(donhang.getDiem() + "");
        txtDiscount.setText(donhang.getGiamGia() + "");
        txtPayment.setText(donhang.getThanhToan() + "");
        txtName.setText(donhang.getTenKH());
        txtPhone.setText(donhang.getSdt());
        txtVoucher.setText(donhang.getMaVoucher());
    }

    private void initDonHangComponents() {
        edits = new JLabel[]{edit1, edit2, edit3, edit4, edit5, edit6, edit7, edit8, edit9, edit10};
        images = new JLabel[]{image1, image2, image3, image4, image5, image6, image7, image8, image9, image10};
        titles = new JLabel[]{title1, title2, title3, title4, title5, title6, title7, title8, title9, title10};
        prices = new JLabel[]{price1, price2, price3, price4, price5, price6, price7, price8, price9, price10};
        numbers = new JLabel[]{number1, number2, number3, number4, number5, number6, number7, number8, number9, number10};
        for (int i = 0; i < 10; i++) {
            list.add(new DonHangComponent(images[i], prices[i], titles[i], numbers[i]));
        }
    }

    private void loadData() {
        listDhct = dhctdao.selectByMaDH(donhang.getMaDH());
        totalPage = (int) Math.ceil(listDhct.size() * 1.0 / skip);
    }

    private void initPagination() {
        Component[] coms = pagination.getComponents();
        if (coms.length > 0) {
            for (Component com : coms) {
                pagination.remove(com);
            }
        }

        pagination.revalidate();
        pagination.repaint();

        for (int i = 0; i < totalPage; i++) {
            JButton btn = new JButton();
            btn.setText(i + 1 + "");
            btn.setSize(30, 30);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    currentPage = Integer.parseInt(btn.getText()) - 1;
                    fillData();
                }
            });
            pagination.add(btn);
        }
    }

    private void fillData() {
        clearData();
        int count = 0;
        int startIndex = currentPage * skip;
        int endIndex = startIndex + skip;
        if (listDhct.size() < endIndex) {
            endIndex = listDhct.size();
        }
        for (int i = startIndex; i < endIndex; i++) {
            list.get(count).show(listDhct.get(i));
            count++;
        }
    }

    private void clearData() {
        for (int i = 0; i < list.size(); i++) {
            list.get(i).clear();
        }
        themNutSuaDonHang();
    }

    private void themNutSuaDonHang() {
        for (int i = 0; i < edits.length; i++) {
            if (i < listDhct.size()) {
                edits[i].setText("Sửa");
            } else {
                edits[i].setText("");
            }
        }
    }

    private void suaThongTin(int index) {
        String value = MsgBox.prompt(this, "Nhập số lượng cần sửa");
        if (value != null) {
            try {
                int soluong = Integer.parseInt(value);
                if (soluong == 0) {
                    if (MsgBox.confirm(this, "Bạn có muốn xoá sản phẩm này không?")) {
                        listXoa.add(listDhct.get(index + currentPage * skip));
                        listDhct.remove(index + currentPage * skip);
                    }
                } else {
                    listDhct.get(index + currentPage * skip).setSoLuong(soluong);
                }
                fillData();
                tinhLaiTien();
            } catch (Exception e) {
                MsgBox.alert(this, "Số lượng không hợp lệ");
            }
        }
    }

    private void tinhLaiTien() {
        int tongTien = 0;
        int tongSoLuong = 0;

        for (DonHangChiTiet dhct : listDhct) {
            tongTien += dhct.getSoLuong() * dhct.getGia();
            tongSoLuong += dhct.getSoLuong();
        }

        int giamGia = discountPercent * tongTien / 100;
        txttongSoLuong.setText(tongSoLuong + "");
        txtDiscount.setText(giamGia + donhang.getDiem() + "");
        txtPayment.setText(tongTien - giamGia + "");
        txtTotal.setText(tongTien + "");
    }

    private void thayDoiThongTinDonHang() {
        if (listDhct.size() <= 0) {
            if (MsgBox.confirm(this, "Đơn hàng không còn sản phẩm. Bạn có muốn xoá đơn hàng này không?")) {
                if (listXoa.size() > 0) {
                    for (DonHangChiTiet dhct : listXoa) {
                        dhctdao.deleteByDonHangChiTiet(dhct);
                    }
                }
                dhdao.delete(donhang.getMaDH());
            }
            this.dispose();
        } else {
            donhang.setThanhToan(Double.parseDouble(txtPayment.getText()));
            donhang.setGiamGia(Integer.parseInt(txtDiscount.getText()));
            dhdao.update(donhang);
            if (listDhct.size() > 0) {
                for (DonHangChiTiet dhct : listDhct) {
                    dhctdao.updateSoluong(dhct);
                }
            }
            MsgBox.alert(this, "Cập nhật thành công");
            this.dispose();
        }
        admain.loadData();
        admain.fillTable();
        if (dhJdialog != null) {
            dhJdialog.loadData();
            dhJdialog.fillTable();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonHangChiTietUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DonHangChiTietUI dialog = new DonHangChiTietUI(new JDialog(), true, donhang, admain, dhJdialog);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel edit1;
    private javax.swing.JLabel edit10;
    private javax.swing.JLabel edit2;
    private javax.swing.JLabel edit3;
    private javax.swing.JLabel edit4;
    private javax.swing.JLabel edit5;
    private javax.swing.JLabel edit6;
    private javax.swing.JLabel edit7;
    private javax.swing.JLabel edit8;
    private javax.swing.JLabel edit9;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image10;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel number1;
    private javax.swing.JLabel number10;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel number3;
    private javax.swing.JLabel number4;
    private javax.swing.JLabel number5;
    private javax.swing.JLabel number6;
    private javax.swing.JLabel number7;
    private javax.swing.JLabel number8;
    private javax.swing.JLabel number9;
    private javax.swing.JPanel pagination;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price10;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoint;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVoucher;
    private javax.swing.JTextField txttongSoLuong;
    private javax.swing.JPanel wrapper1;
    private javax.swing.JPanel wrapper10;
    private javax.swing.JPanel wrapper2;
    private javax.swing.JPanel wrapper3;
    private javax.swing.JPanel wrapper4;
    private javax.swing.JPanel wrapper5;
    private javax.swing.JPanel wrapper6;
    private javax.swing.JPanel wrapper7;
    private javax.swing.JPanel wrapper8;
    private javax.swing.JPanel wrapper9;
    // End of variables declaration//GEN-END:variables

}
