/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.thecoffee.ui;

import com.formdev.flatlaf.FlatLightLaf;
import com.thecoffee.components.FormField;
import com.thecoffee.components.InputField;
import com.thecoffee.components.PasswordField;
import com.thecoffee.dao.KhachHangDAO;
import com.thecoffee.dao.NhanVienDAO;
import com.thecoffee.dao.TaiKhoanDao;
import com.thecoffee.entity.NhanVien;
import com.thecoffee.entity.SavedAccount;
import com.thecoffee.entity.TaiKhoan;
import com.thecoffee.resource.Auth;
import com.thecoffee.resource.Constant;
import com.thecoffee.utils.MsgBox;
import com.thecoffee.utils.XFile;
import com.thecoffee.utils.XImage;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author daung
 */
public class Login extends javax.swing.JFrame {

    private TaiKhoanDao tkdao = new TaiKhoanDao();
    private KhachHangDAO khdao = new KhachHangDAO();
    private NhanVienDAO nvdao = new NhanVienDAO();
    List<FormField> listInputs = new ArrayList<>();
    private boolean isRememberAcc = true;
    private boolean isShowPass = false;
    private SavedAccount saveAcc = new SavedAccount("", "");

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        cboGhiNho.setSelected(isRememberAcc);
        txtPassword.setEchoChar('\u25cf');
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(".\\appIcon.png"));
        loadInfo();
    }

    public void setData(String userName, String Pass) {
        txtEmail.setText(userName);
        txtPassword.setText(Pass);
    }

    private boolean isValidate() {
        boolean flag = true;
        InputField email = new InputField(txtEmail, error1, InputField.EMAIL, "Email không đúng định dạng");
        PasswordField password = new PasswordField(txtPassword, error2, "Mật khẩu không được để trống");

        if (!email.isValid()) {
            flag = false;
        }

        if (!password.isValid()) {
            flag = false;

        }

        return flag;
    }

    private void loadInfo() {
        try {
            saveAcc = (SavedAccount) XFile.readObject(Constant.SAVE_ACC_PATH);
        } catch (Exception e) {
        }
        if (saveAcc != null) {
            txtEmail.setText(saveAcc.getUserName());
            txtPassword.setText(saveAcc.getPassWord());
        }
    }

    public void login() {
        if (isValidate()) {
            TaiKhoan tk = tkdao.selectByEmail(txtEmail.getText());
            if (tk == null) {
                MsgBox.alert(this, "Email chưa được đăng ký");
            } else {
                Auth.tk = tk;
                String password = new String(txtPassword.getPassword());
                if (password.equals(tk.getMatKhau())) {
                    if (saveAcc == null) {
                        saveAcc = new SavedAccount("", "");
                    }
                    if (isRememberAcc) {
                        saveAcc.setUserName(txtEmail.getText());
                        saveAcc.setPassWord(new String(txtPassword.getPassword()));
                    } else {
                        saveAcc.setUserName("");
                        saveAcc.setPassWord("");
                    }
                    try {
                        XFile.writeObject(Constant.SAVE_ACC_PATH, saveAcc);
                    } catch (IOException ex) {
                    }
                    Auth.role = tk.getVaiTro();
                    NhanVien nv = nvdao.selectById(tk.getMaTK());
                    if (nv != null) {
                        Auth.userName = nv.getTen();
                    }
                    Auth.setData(tk);
                    this.dispose();
                    new AdminMain().setVisible(true);
                } else {
                    MsgBox.alert(this, "Mật khẩu không chính xác");
                }
            }
        }
    }

    void showHidePass() {
        if (isShowPass) {
            txtPassword.setEchoChar((char) 0);
            XImage.setLabelIcon(lblShow, "eye.png");
        } else {
            txtPassword.setEchoChar('\u25cf');
            XImage.setLabelIcon(lblShow, "blind.png");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboGhiNho = new javax.swing.JCheckBox();
        btnResetPassword = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        lblShow = new javax.swing.JLabel();
        txtEmail = new com.thecoffee.components.TextField();
        txtPassword = new com.thecoffee.components.PasswordField1();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");

        kGradientPanel1.setkEndColor(new java.awt.Color(60, 14, 14));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(248, 244, 244));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Sign In");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        cboGhiNho.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cboGhiNho.setForeground(new java.awt.Color(102, 0, 0));
        cboGhiNho.setText("Remember ?");
        cboGhiNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGhiNhoActionPerformed(evt);
            }
        });
        jPanel1.add(cboGhiNho, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(102, 0, 0));
        btnResetPassword.setText("Forget Password ");
        btnResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(btnResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 90, 20));

        error2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        error2.setForeground(new java.awt.Color(255, 51, 51));
        error2.setText(" ");
        jPanel1.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 280, -1));

        error1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        error1.setForeground(new java.awt.Color(255, 51, 51));
        error1.setText(" ");
        jPanel1.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, -1));

        lblShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thecoffee/icons/blind.png"))); // NOI18N
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowMouseClicked(evt);
            }
        });
        jPanel1.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        txtEmail.setLabelText("Email");
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, -1));

        txtPassword.setLabelText("Password");
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Login with FaceID");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 180, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Sign In");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 100, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thecoffee/icons/PNGKhothietke.net-02376 (1).png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGhiNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGhiNhoActionPerformed
        isRememberAcc = cboGhiNho.isSelected();
    }//GEN-LAST:event_cboGhiNhoActionPerformed

    private void btnResetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPasswordMouseClicked
        new QuenMatKhau(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnResetPasswordMouseClicked

    private void lblShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseClicked
        // TODO add your handling code here:
        isShowPass = !isShowPass;
        showHidePass();
    }//GEN-LAST:event_lblShowMouseClicked

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new RecognizeFace(new JFrame(), true, this).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        login();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnResetPassword;
    private javax.swing.JCheckBox cboGhiNho;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblShow;
    private com.thecoffee.components.TextField txtEmail;
    private com.thecoffee.components.PasswordField1 txtPassword;
    // End of variables declaration//GEN-END:variables
}
